site_name: Boilerplate
theme:
  name: material
  icon:
    logo: material/book-open
  features:
    - navigation.instant
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg